/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: im2pStCKgPbRXfmQeJTnXf
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsur9LaxRnLose } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ur9LaxRnLOSE/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsur9LaxRnLose
});
